### ISSUE TITLE
rhx_gis error

### ISSUE THREAD

**Issue by RVLVT** [papeta/instagram_activity_hunter#1]
it give me this error:

Traceback (most recent call last):
  File "activityhunter.py", line 262, in <module>
    main()
  File "activityhunter.py", line 258, in main
    a.scrape()
  File "activityhunter.py", line 106, in scrape
    self.query_timeline(user)            
  File "activityhunter.py", line 110, in query_timeline
    sharedData = self.get_sharedData(username)
  File "activityhunter.py", line 233, in get_sharedData
    self.rhx_gis = sharedData['rhx_gis']
KeyError: 'rhx_gis'

**Comment by novitae** [comment]
same
